version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - test:
          post:
            yarn jest --coverage
            coveralls