version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: Run test
          command: yarn run test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Post to codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test
