version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: Run test
          command: yarn jest --coverage
      - store_artifacts:
          path: /coverage
      - run:
          name: Post to coveralls
          command: yarn run coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build